In [ ]:
import math
import numpy as np
import csv
import random

#print(np.random.multinomial(100, [31/100., 31/100., 31/100., 1/100., 1/100., 1/100., 1/100., 1/100., 1/100., 1/100.]))

In [ ]:
y = [1, 33, 0, 0, 5, 34, 7, 1, 9, 10]

def generate_multinomial(x):
  x = np.ndarray.tolist(np.array(x)/100.0)
  return np.random.multinomial(100, x)

print(generate_multinomial(y))


def generate_solution_class(x, n):
  solutions = np.empty([n,10])
  for i in range(n):
    solutions[i] = generate_multinomial(x)
  return solutions

#print("\n")
#print(generate_solution_class(y, 30))

[ 0 34  0  0 10 21  5  2 12 16]


In [ ]:
### STRATEGY BASED SOLUTIONS ####

EC1 = [34, 33, 33, 0, 0, 0, 0, 0, 0, 0] 
EC2 = [0, 34, 33, 33, 0, 0, 0, 0, 0, 0]
EC3 = [0, 0, 34, 33, 33, 0, 0, 0, 0, 0] #Doing Extreme Clustering Beyond this point is risky, if they occupy all of the top 3 you're done
EC4 = [0, 0, 0, 34, 33, 33, 0, 0, 0, 0]
EC5 = [0, 0, 0, 0, 34, 33, 33, 0, 0, 0]


C1 = [31, 31, 31, 1, 1, 1, 1, 1, 1, 1]
C2 = [1, 31, 31, 31, 1, 1, 1, 1, 1, 1]
C3 = [1, 1, 31, 31, 31, 1, 1, 1, 1, 1]
C4 = [1, 10, 1, 28, 28, 28, 1, 1, 1, 1]
C5_1 = [1, 10, 1, 1, 28, 28, 28, 1, 1, 1]
C5_2 = [1, 1, 10, 1, 28, 28, 28, 1, 1, 1]
C6 = [1, 1, 10, 1, 1, 28, 28, 28, 1, 1]
C7_1 = [12, 1, 1, 8, 1, 1, 25, 25, 25, 1] #As we have seen above, as you get farther away less troops tend to be allocated 
C7_2 = [1, 12, 1, 8, 1, 1, 25, 25, 25, 1]
C7_3 = [1, 12, 1, 1, 8, 1, 25, 25, 25, 1]
C7_4 = [1, 1, 12, 8, 1, 1, 25, 25, 25, 1]
C7_5 = [1, 1, 12, 1, 8, 1, 25, 25, 25, 1]
C7_5 = [1, 1, 12, 1, 1, 8, 25, 25, 25, 1]

CB1_1 = [31, 1, 1, 31, 1, 1, 31, 1, 1, 1]
CB1_2 = [28, 1, 1, 28, 1, 1, 28, 1, 1, 10]
CB2_1 = [1, 31, 1, 1, 31, 1, 1, 31, 1, 1]
CB2_2 = [1, 28, 1, 1, 28, 1, 1, 28, 1, 10]
CB3_1 = [1, 1, 31, 1, 1, 31, 1, 1, 31, 1]
CB3_2 = [1, 1, 28, 1, 1, 28, 1, 1, 28, 10]

DC_1 = [20, 20, 20, 1, 1, 12, 12, 12, 1, 1]
DC_2 = [1, 20, 20, 20, 1, 1, 12, 12, 12, 1]
DC_3 = [1, 1, 20, 20, 20, 1, 1, 12, 12, 12] #Least likely approach of the three

U = [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

E1 = [0, 0, 35, 1, 22, 22, 17, 1, 1, 1]
E2 = [0, 35, 0, 22, 22, 17, 1, 1, 1, 1]
E3 = [35, 0, 0, 22, 22, 17, 1, 1, 1, 1]



In [ ]:
### GENERATE SAMPLES OF SOLUTIONS ###

a1 = generate_solution_class(EC1, 100)
a2 = generate_solution_class(EC2, 100)
a3 = generate_solution_class(EC3, 100)
a4 = generate_solution_class(EC4, 30)
a5 = generate_solution_class(EC5, 30)
EC_solutionset = np.concatenate((a1, a2, a3), axis=0)

b1 = generate_solution_class(C1, 70)
b2 = generate_solution_class(C2, 70)
b3 = generate_solution_class(C3, 70)
b4 = generate_solution_class(C4, 70)
b5_1 = generate_solution_class(C5_1, 70)
b5_2 = generate_solution_class(C5_2, 70)
b6 = generate_solution_class(C6, 70)
b7_1 = generate_solution_class(C7_1, 50)
b7_2 = generate_solution_class(C7_2, 50)
b7_3 = generate_solution_class(C7_3, 50)
b7_4 = generate_solution_class(C7_4, 50)
b7_5 = generate_solution_class(C7_5, 50)
C_solutionset = np.concatenate((b1, b2, b3, b4, b5_1, b5_2, b6, b7_1, b7_2, b7_3, b7_4, b7_5), axis=0)

c1_1 = generate_solution_class(CB1_1, 50)
c1_2 = generate_solution_class(CB1_2, 50)
c2_1 = generate_solution_class(CB2_1, 50)
c2_2 = generate_solution_class(CB2_2, 50)
c3_1 = generate_solution_class(CB3_1, 50)
c3_2 = generate_solution_class(CB3_2, 50)
CB_solutionset = np.concatenate((c1_1, c1_2, c2_1, c2_2, c3_1, c3_2), axis=0)

d1 = generate_solution_class(DC_1, 60)
d2 = generate_solution_class(DC_2, 60)
d3 = generate_solution_class(DC_3, 40)
DC_solutionset = np.concatenate((d1, d2, d3), axis=0)

e1 = generate_solution_class(E1, 90)
e2 = generate_solution_class(E2, 90)
e3 = generate_solution_class(E3, 50)
E_solutionset = np.concatenate((e1, e2, e3), axis=0)


U_solutionset = generate_solution_class(U, 30)

SolutionSet = np.concatenate((EC_solutionset, C_solutionset, CB_solutionset, DC_solutionset, U_solutionset, E_solutionset), axis = 0)

header = ["Castle 1", "Castle 2", "Castle 3", "Castle 4", "Castle 5", "Castle 6", "Castle 7", "Castle 8", "Castle 9", "Castle 10"]
header = np.array(header)

with open('solutions.csv', 'w', newline = '') as file:
  writer = csv.writer(file)
  writer.writerow(header)
  writer.writerows(SolutionSet)


In [ ]:
def solution_wins(x, y):
  x_total = 0
  y_total = 0
  last_victor = "none"
  consecutive_wins = 0
  
  for i in range(10):

    if x[i] > y[i]:
      x_total += i + 1
      if last_victor == "x" and consecutive_wins == 2:
        x_total += sum(val for val in range(i+2,11))
        break
      else:
        consecutive_wins = consecutive_wins + 1 if last_victor == "x" else 1
        last_victor = "x"

    elif x[i] < y[i]:
      y_total += i + 1
      if last_victor == "y" and consecutive_wins == 2:
        y_total += sum(val for val in range(i+2,11))
        break
      else:
        consecutive_wins = consecutive_wins + 1 if last_victor == "y" else 1
        last_victor = "y"

    else:
      consecutive_wins = 0
      last_victor = "none"

  return x_total > y_total


#print(newstrat_wins([34, 33, 33, 0, 0, 0, 0, 0, 0, 0],[0, 34, 0, 1, 1, 1, 1, 1, 1, 60]))
#print("\n")
#print(newstrat_wins([10, 10, 10, 10, 20, 0, 0, 0, 20, 20],[20, 0, 10, 5, 10, 5, 10, 20, 0, 0]))
#print("\n")
#print(newstrat_wins([10, 10, 10, 10, 10, 10, 10, 10, 10, 10],[20, 5, 10, 10, 5, 10, 20, 10, 10, 10]))
        


In [ ]:
def win_rate(solution, allSolutions):
  wins = 0
  for i in range(allSolutions.shape[0]):
    wins = wins+1 if solution_wins(solution, allSolutions[i]) else wins 
  return wins/(allSolutions.shape[0])

def get_neighbor(solution):
  neighbor = solution.copy()
  nonzero_indices = []
  for i in range(10):
    if solution[i] >0:
      nonzero_indices.append(i)
  index_to_remove_from = random.choice(nonzero_indices)
  index_to_add_to = random.randint(0,9)
  neighbor[index_to_remove_from] = neighbor[index_to_remove_from] - 1
  neighbor[index_to_add_to] = neighbor[index_to_add_to] + 1
  return neighbor
  
def simulated_anneal(currentSolution, originalSolutions, improvedSolutions, overallBestRate, overallBestSolution ):
  modifiedSolution = get_neighbor(currentSolution)
  modifiedRate = (win_rate(modifiedSolution, originalSolutions) + win_rate(modifiedSolution, improvedSolutions))/(2)
  currentRate = (win_rate(currentSolution, originalSolutions) + win_rate(currentSolution, improvedSolutions))/(2)
  if modifiedRate > overallBestRate:
    overallBestRate = modifiedRate
    overallBestSolution = modifiedSolution
  if random.random() < .05 or modifiedRate > currentRate:
    currentSolution = modifiedSolution
    np.vstack([improvedSolutions , modifiedSolution])

  return currentSolution, originalSolutions, improvedSolutions, overallBestRate, overallBestSolution




In [ ]:
def get_effectiveness_uniform(strat1):
  effectiveness = 0
  wins = 0
  for i in range(strat1.shape[0]):
    for j in range(U_solutionset.shape[0]):
      wins = wins+1 if solution_wins(strat1[i], U_solutionset[j]) else wins

  return wins/(strat1.shape[0] * U_solutionset.shape[0])

def get_effectiveness(strat1, strat2): 

  wins = 0
  for i in range(strat1.shape[0]):
    for j in range(strat2.shape[0]):
      wins = wins+1 if solution_wins(strat1[i], strat2[j]) else wins

  return wins/(strat1.shape[0] * strat2.shape[0])

def get_rate_for_solution(solution, allSolutions): 

  wins = 0
  for i in range(len(solution)):
    for j in range(allSolutions.shape[0]):
      wins = wins+1 if solution_wins(solution, allSolutions[j]) else wins

  return wins/(allSolutions.shape[0])


#print(get_effectiveness(d2, a1))



In [ ]:
sol = [0, 31, 32, 33, 1, 0, 3, 0, 0, 0]
sol = np.array(sol)
print(sol)
print(get_neighbor(sol))
print(win_rate(get_neighbor(sol), EC_solutionset))

[ 0 31 32 33  1  0  3  0  0  0]
[ 0 31 32 33  1  0  3  0  0  0]
0.8033333333333333


In [ ]:
print(get_rate_for_solution(np.array([2, 15, 41, 27,  3,  3,  3,  1,  3,  2]), SolutionSet))

9.357954545454545


In [ ]:
solution_wins([0, 1, 42, 27, 12, 5, 6 ,3, 4, 0], [5, 23, 42, 14, 0, 4, 3, 4, 4, 1])

True

In [ ]:
import threading

current = np.array([10,10,10,10 ,10, 10, 10, 10, 10, 10])
originalSolutionSet = SolutionSet
improvedSolutionSet = SolutionSet.copy()
bestWinRate = 0
winningSolution = np.array([10,10,10,10 ,10, 10, 10, 10, 10, 10])

def printit():
  threading.Timer(10.0, printit).start()
  print(bestWinRate, winningSolution)

printit()

while(True):
  current, originalSolutionSet, improvedSolutionSet, bestWinRate, winningSolution = simulated_anneal(current, originalSolutionSet, improvedSolutionSet, bestWinRate, winningSolution)


0 [10 10 10 10 10 10 10 10 10 10]
0.4681818181818182 [ 6 16 13 15  8 10  9  7  2 14]
0.5272727272727272 [ 3 20 17 16  5  8 12  3  0 16]
0.58125 [ 4 20 23 19  3  7  8  2  2 12]
0.7636363636363637 [ 3 21 32 22  2  4  4  1  2  9]
0.8960227272727272 [ 4 19 38 24  3  2  3  0  3  4]
0.925 [ 3 18 41 24  3  2  3  1  3  2]
0.9318181818181818 [ 3 17 40 25  3  3  2  2  3  2]
0.9346590909090909 [ 2 15 41 25  3  4  3  3  3  1]
0.9352272727272727 [ 2 16 41 26  3  3  3  3  3  0]
0.9392045454545455 [ 1 14 41 29  3  2  3  2  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 1 15 41 29  3  2  3  1  3  2]
0.9403409090909091 [ 